In [1]:
sentence = """Thomas Jefferson began building Monticello at the age of 26."""
sentence.split()

['Thomas',
 'Jefferson',
 'began',
 'building',
 'Monticello',
 'at',
 'the',
 'age',
 'of',
 '26.']

In [2]:
import numpy as np
token_sequence = str.split(sentence)
vocab = sorted(set(token_sequence))

In [3]:
vocab

['26.',
 'Jefferson',
 'Monticello',
 'Thomas',
 'age',
 'at',
 'began',
 'building',
 'of',
 'the']

In [4]:
num_tokens = len(token_sequence)
vocab_size = len(vocab)

In [5]:
print(num_tokens, vocab_size)

10 10


In [6]:
onehot_vectors = np.zeros((num_tokens, vocab_size), int)

In [7]:
for i, word in enumerate(token_sequence):
   onehot_vectors[i, vocab.index(word)] = 1

In [8]:
onehot_vectors

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
onehot_vectors[0]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [10]:
onehot_vectors[9]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])